### ISSUE TITLE
Rewrite using a Go docker client

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#10]
Instead of executing commands, it'be nicer to use a docker client. I'm thinking of https://github.com/fsouza/go-dockerclient at the moment.

**Comment by michaelsauter** [comment]
Time has passed and I don't see this as a priority anymore. In fact, I kind of like the current state since the verbose output of Crane can be quite useful. There are bigger issues to address, so closing this for now.

**Comment by gregwebs** [comment]
Fine with me: crane has been working flawlessly for my use case.
