### ISSUE TITLE
Crane cause docker to re-pull remote image every time provision being run

### ISSUE THREAD

**Issue by phuongnd08** [michaelsauter/crane#104]
I'm using dockerfile/redis as one of my container and every couple of day when I run crane provision, I see new layer of redis (around 80MB, which is a pain to download over my internet connection over and over) because crane invoke `docker pull dockerfile/redis`. This really cause the provision a pain in the ass. I temporary workaround this by explicitly create Dockerfile which contain a single FROM definition for any of the remote images.

**Comment by michaelsauter** [comment]
Closing since building images and the behaviour of lift might change with #195.
