### ISSUE TITLE
clone git repo when no dockerfile

### ISSUE THREAD

**Issue by gregory** [michaelsauter/crane#111]
Would be awesome to get this feature: 
if there is no Dockerfile in the dockerfile directory, clone the repo given by the yml option git: git_repo then build the image from the Dockerfile

**Comment by dreamcat4** [comment]
@gregory Excuse me. But the `docker build` comand accept GIT repo urls for the build context argument.

So you can already put in your crane.yml:

```yaml
containers:
  myapp:
    dockerfile: https://github.com/account/repo
```

And that will tell docker to download `account/repo` from github and use as the build context.

*However this method will only work if your Dockerfile happens to be located in the root folder of the git repo. It does not let you specify the Dockerfile location idependantly inside the git repo. E.g. for multiple Dockerfiles / image variants.* For that, crane needs 2 parameters. One to set the `build context` location (e.g. to your git url), and the other variable to set the `Dockerfile` location within the repo. In other words `docker build --file=$dockerfile $location`. There is an un-merged feature branch which implements that.

**Comment by gregory** [comment]
waw! this is awesome!
Just tried it out. Looks like we need to append .git at the end of the repo: 
`dockerfile: https://github.com/account/repo.git`
Would be awesome to be able to pass over a branch name! Sounds like [this isn't working](http://stackoverflow.com/questions/25509828/can-a-docker-build-use-the-url-of-a-git-branch) for now.
