### ISSUE TITLE
Share same image between targets

### ISSUE THREAD

**Issue by phuongnd08** [michaelsauter/crane#118]
I'm building a rails app, in which the sidekiq container and the web container will share the same image, only the launch command will be different.
I would like to tell crane that the two target actually share the same images, so it doesn't need to build the image over and over (though docker will use the cache so it won't take long). This would save the time that docker is sending all the files to the daemon repeatedly. This pain grow as we have a lot of containers sharing the same images, only different commands.

**Comment by tpaz** [comment]
+1, in some cases we want to build on top of a common image where that image is not intended to run a container on itself. Such dependency will cause crane to fail "lift" if that image is not already built manually.

**Comment by michaelsauter** [comment]
Closing since there won't be more build related features in Crane, see #195 .
