### ISSUE TITLE
Entrypoint should support array (docs say string)

### ISSUE THREAD

**Issue by christianromney** [michaelsauter/crane#135]
Docker's ENTRYPOINT supports an exec form (looks like a JSON array). When this form of entry point is used AND the same form of CMD is used, then cmd is interpreted to be an additional argument to entrypoint. This lets you specify the binary to execute in a base container and choose its params/configs in a derived image.

    ENTRYPOINT ["cat"]
    CMD ["/var/log/syslog"]

The example is contrived, but the use case is real.

**Comment by michaelsauter** [comment]
Ah okay. Must have changed after entrypoint was added to Crane or the Docker docs were wrong at the time.

Do you want to contribute it? Should be similar to the other params, so you could get guidance from those ...

**Comment by michaelsauter** [comment]
@christianromney ping

**Comment by christianromney** [comment]
Woops Hi @michaelsauter I've been a bit swamped. Will try to contribute this tonight/tomorrow. Does that work? :)

**Comment by michaelsauter** [comment]
Sure, no worries! I was just going through the open issues and found this one, so thought I'll check whether you still want to work on it. No rush!

**Comment by dreamcat4** [comment]
+1

**Comment by bjaglin** [comment]
AFAIK, the array ENTRYPOINT syntax is only supported in the `Dockerfile` DSL, not on the `docker run` CLI.

See previous discussions around that:
* https://github.com/michaelsauter/crane/pull/73
* https://github.com/docker/docker/pull/7268
