### ISSUE TITLE
Please provide security configuration keyword

### ISSUE THREAD

**Issue by marmotz** [michaelsauter/crane#137]
https://docs.docker.com/reference/run/#security-configuration

or a generic way to set "unknown options" ?

**Comment by michaelsauter** [comment]
Thanks for the pointer, must be a fairly new addition :)
I usually want to map Crane's config 1:1, so a `security-opt` option would be best IMO. Do you have time / interest to contribute it?

**Comment by marmotz** [comment]
Yes but I don't know Go.

I'll try :)

**Comment by michaelsauter** [comment]
Cool! Go is pretty easy to get into, and you should be able to just follow the example of the other options. Let me know how you go.

**Comment by bjaglin** [comment]
https://github.com/michaelsauter/crane/pull/145

**Comment by bjaglin** [comment]
and https://github.com/michaelsauter/crane/pull/147 for a more pragmatic/generic way to set unsupported/new options

**Comment by michaelsauter** [comment]
Closed via #145.
