### ISSUE TITLE
Investigate vendoring options

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#138]
I want to introduce some dependency management, and https://github.com/gophergala/nut looks perfect so far.

**Comment by michaelsauter** [comment]
Still an issue. http://getgb.io looks like it's gaining some traction and I like the general idea of it.

**Comment by missedone** [comment]
GB is quite good and really easy to use from my view, but one thing you might concern is GB is not go gettable, for more detail see discussion: https://github.com/constabulary/gb/issues/284

**Comment by michaelsauter** [comment]
Right. In the meantime, Go has added experimental support for vendoring and that's an option now too. Since there are no pressing issues right now, I'd like to leave this question open for a little longer and see what happens :)

**Comment by bjaglin** [comment]
I guess https://github.com/michaelsauter/crane/blob/master/deps is obsolete?

**Comment by michaelsauter** [comment]
That should be still what I'm building from since I didn't update any dependencies. However, I'm not really using it right now either.

**Comment by michaelsauter** [comment]
Given Go 1.6 is out and has vendor support by default, I intend to use that now.

The plan is to:

1. Upgrade to Go 1.6
2. Add all dependencies as git submodules (I'll manage them locally with https://github.com/dpw/vendetta)
3. Checkout the versions as specified in the `deps` file
4. Delete the `deps` file
5. Publish

**Comment by bjaglin** [comment]
:+1:
