### ISSUE TITLE
support docker exec command - enhancement

### ISSUE THREAD

**Issue by tpaz** [michaelsauter/crane#141]
In recent versions of Docker a new and very useful command was introduced: exec.
https://docs.docker.com/reference/commandline/cli/#exec
It would be very helpful if crane could support that command like it supports "run: ".
I found myself bouncing into a wall when I needed that extra orchestration capability to execute a command on a container just before or after another container is lifted or built, rather than statically coding it into Docker file (i.e. required Runtime operation rather than build time).
Supporting multiple instances of exec would be even greater.

**Comment by michaelsauter** [comment]
I haven't consider to include `exec` into Crane as it is targeted at one specific container, and I don't see a use case against multiple containers. I'm not quite sure what your use case is, maybe you can show an example?

**Comment by tpaz** [comment]
1. run a django CLI "createsuperuser" after both django and PSQL DB are up and running
2. nginx reload when any other container is re-lifted and nginx depends on it (dns cache)
actually how exactly is crane considering multiple containers of the same kind use-case?
Fig has a nice solution "scale", I haven't seen it in crane, but that's ok for development environment purpose. exec support allows extra flexibility to run something beyond the run CMD or ENTRYPOINT

**Comment by michaelsauter** [comment]
For 1), what would a `crane exec` give you over a `docker exec`?

About 2), you're right, Crane does not support a `scale` option, but could ... I just haven't found a need for it. Happy to include it though.

**Comment by srangwal** [comment]
Regarding 2. With fig I have found ```scale``` to be very useful to create a mini-datacenter setup locally on my desktop for development purposes. There has been discussion of adding an ```initial_scale``` which is equally useful.  https://github.com/docker/fig/pull/630

**Comment by bjaglin** [comment]
A side note regarding 2): I personally don't have a strong need for `scale`, which IMHO mixes up functional mapping and infrastructure:
* If you want to have several instances of a container for a production environment, you probably should be using a more complex orchestrator such as Kubernetes;
* If you want to _functionally_ test locally failover or load balancing, you might just as well duplicate a container twice or three times in the config. I conceed that `scale` is a nice shortcut to avoid boilerplate in that use case, but that's nothing that can't be done.

**Comment by dreamcat4** [comment]
Just a thought about `scale` feature in crane:

If we could include multiple `crane.yml` files into each other, then it would possible to write a script to generate sub-`crane.yml`(s) with auto-filled instances. E.g. with a templated IP address and everything else like that.

I guess it wouldn't be 'true' integrated scaling support though. But you could also auto-generate a crane group in for each collection of instances. So they could be brought up / down at same time etc. You could even also just as easily create groups for controlling slices too (e.g. everything that is instance 1, etc).

The benefit of doing a `scale` feature that way is the same `crane.yml` include feature also serves other uses too. E.g restructuring larger projects when having one file gets too big. Or overriding values in the underlying `crane.yml` etc.

**Comment by michaelsauter** [comment]
I'm going to close this since I don't (yet) understand the benefits of a `crane exec`. A potential `scale` feature can be discussed separately.
