### ISSUE TITLE
Spurious CI failure due to version bump

### ISSUE THREAD

**Issue by mbrock** [michaelsauter/crane#150]
Hello!

We use Crane quite happily, and this is only a minor annoyance, but this morning I pushed some innocuous code that made our continous integration server report a failure.

The failure was that Crane suddenly wasn't executable!

Our CI script downloads Crane using the `download.sh` script, and this had silently downloaded some error page or something instead of an actual program.

Clicking "rebuild" solved the problem.

Just letting you know. :) Maybe there's a simple change in your release procedure that could ensure that the download script always works?

**Comment by michaelsauter** [comment]
Oh! Sorry about that :)

When I push a new version, the release script points to a new "GitHub release". But that doesn't exist at the time I push the tag, and then I need a few minutes to finish the release notes and upload the binaries. It sounds like your CI tried to download Crane just at that time!

I probably could update the `download.sh` script after the GitHub release is done ... just never thought that short time mattered :) Will keep that in mind for the next release.

**Comment by mbrock** [comment]
Yeah, that's what I guessed, and I was quite amused at the seeming improbability.

It was a whole workday of spurious and unlikely problems, but a beautiful Stockholm sunset set everything right again.

**Comment by michaelsauter** [comment]
@mbrock You might want to change that setup anyway even if I "fix" this ... since you are currently relying on a) GitHub being up and b) me not releasing backwards incompatible versions of Crane. In fact, 1.1.0 might contain a breaking change if you relied on error/verbose output being dumped to STDOUT.

**Comment by mbrock** [comment]
@michaelsauter Excellent point! We already depend on GitHub in a few other ways, but I notice that `download.sh` supports overriding `VERSION` in the environment; just setting that seems pretty reasonable.

**Comment by dbrock** [comment]
:laughing:  :beers: 

So I guess it would be simpler for us just to do this:

    curl -L https://github.com/michaelsauter/crane/releases/download\
    /v1.1.0/crane_linux_amd64 -o /usr/local/bin/crane && chmod +x $_
