### ISSUE TITLE
Support new Docker 1.6.0 features - Labels

### ISSUE THREAD

**Issue by dreamcat4** [michaelsauter/crane#160]
Hi,
Labels is a new feature coming in Docker 1.6.0. It's been merged today.

https://github.com/docker/docker/pull/9882

Similar to ENV vars. But it seems useful enough.

**Comment by dreamcat4** [comment]
Update: Here is the changelog for all of the new 1.6.0 features (not just 'Labels'):

https://github.com/jfrazelle/docker/commit/746e83023052e32b2cba8fccf67b6232e5c86886

 Building images from an image ID

+ `commit --change` to apply specified Dockerfile instructions while committing the image
+ `import --change` to apply specified Dockerfile instructions while importing the image

#### Client
+ Windows Support

#### Runtime
+ Container and image Labels
+ `--cgroup-parent` for specifying a parent cgroup to place container cgroup within
+ Logging drivers, `json-file` or `syslog`
+ Pulling images by ID
+ `--ulimit` to set the ulimit on a container

**Comment by michaelsauter** [comment]
@dreamcat4 Interested in contributing the labels? Apart from that, cgroup-parent, log and ulimit should be added as well to Crane. I'll see if I can get to it but happy if someone wants to help out!

**Comment by dreamcat4** [comment]
Again sorry - but am busy focused elsewhere (when you actually need me to do something!). Indeed labels is on my own agenda, but not until much later on after a heap of other stuff.

I think I can justify working on labels. If before that you look over my previous finished contribution. Which was for seperate `dockerfile` and `location` parameters to specify the docker build context independently. If you can't merge it then at least review it / comment on it.

You also need to respond to my previous comments / concerns about the project maintainership. It is not really such a one-man show anymore if you also need other people to help keep things up to date.

Then yes. After that over with, then I would be happy to work on labels feature. And try to improve the readme file too (as directed).
