### ISSUE TITLE
boot2docker support

### ISSUE THREAD

**Issue by mishak87** [michaelsauter/crane#166]
- [ ] 386 binaries - it is run in 32b userspace
- [ ] use sh instead of bash for download script - no bash

**Comment by mishak87** [comment]
I can provide pull request if necessary.

**Comment by bjaglin** [comment]
Could you provide more details with the use case? I am not very familiar with boot2docker, but isn't Docker only available on x64 architecture - meaning that boot2docker is not 32bits?

**Comment by mishak87** [comment]
https://github.com/boot2docker/boot2docker-cli/issues/264
> boot2docker currently uses Tiny Core Linux, which provides a 64-bit kernel and a 32-bit user-space.

**Comment by bjaglin** [comment]
Oh, I wasn't aware of that userspace twist - thanks.

**Comment by michaelsauter** [comment]
@mishka87 Pull request is welcome. I don't use boot2docker, but happy to merge the changes as they seem small enough.

**Comment by mishak87** [comment]
Thanks will try to do it over the weekend.

**Comment by mishak87** [comment]
Finally got the time to do it #184 and #185.

**Comment by michaelsauter** [comment]
Closing this since #185 is merged already. Hesitant about #184 though, but that scripts needs to be rewritten anyway ...
