### ISSUE TITLE
Proposal: ability to declare the readiness of a container

### ISSUE THREAD

**Issue by adrianhurt** [michaelsauter/crane#171]
I've decided to open another issue to continue with #170 regarding this. I'll try to explain the case. Now Docker CLI only cares about starting a new container. What is in this container and how to use it is your problem. It's logical. And Crane (or Compose-Fig) is all about managing a multi-container application. It allows you to define all the information about every container in a single file. And one of the best features is the possibility of lifting the whole project using the dependency management to know the correct order to start each container. Then all the containers are started sequentially. And also, if you try to lift a specific container with crane, it checks before if its dependent containers are running or not. Ok, that sounds perfect!

However, in some cases it's not enough. In my opinion, I think there is something very important we are forgetting. The most important thing in a container is the process that runs inside. So the dependencies between containers shouldn't always be limited to the status of its dependent containers, but in some cases also to its processes running inside.

I've been using a lot the same example in other issues, but I think it's very common for this issue. It's the typical example of a `db` container and a `web` linked to that. The db-server inside the `db` container runs when the container is started, but it takes a while to be ready to use. If you start immediately the `web` container it will fail because it can't connect to the database. As I commented in the other issue, there are some possible ways to workaround this problem: using extra _waiters_ containers with fake dependencies, or adding some logic inside the execution of each container to wait until everything is ready and then execute the main process. But IMHO, they are not very elegant solutions. I think it's more logical to give that control and decisions to crane.

So my proposal is to add an optional declaration that lets to each container to define its own way to know if it's ready to use or not. It could be done easily using the `docker exec container cmd_to_eval` command directly to each container. If the result is an _0 status_ then it's considered as ready. It could be something like this:
```
containers:
  db:
    …
    ready-when: mysql -u root -prootpass database -e "show tables"
  web:
    run:
      link: ["db:db"]
      …
    ready-when: curl localhost:9000 | grep '<h1>Home</h1>'
```
Then every time a container is lifted, crane could check before whether its dependent containers are running and also if they are really ready to use. And if you lift them with cascading, then crane could lift before each dependent container using the graph order and waiting for their readiness if necessary (echoing that and with a timeout, of course).

Obviously, this is only an idea to discuss, but I think it could be very interesting and it shouldn't be too difficult to implement.

**Comment by dreamcat4** [comment]
I like the 'process-oriented' focus and can see the value in this. Indeed this is a very real problem. But it is also a general docker problem. So it would be best to check up on the situation over at `docker/docker` to make sure we don't introduce something that eventually becomes deprecated or incompatible with whatever the future official docker solution to the problem end up being. Because we know they are thinking about improving this too in official docker toolset.

But we also have pre-start container hooks. So with the hooks feature you could potentially run a command in a pre-start hook that waits or blocks until all of it's dependant containers are ready / online.

I should also say - there is something key to discuss here: If a container can always be able to know (from inside itself) if it's service are actually ready and available. Or if in certain cases that is something which can only be deduced from the outside. E.g. a networking thing.

Wheras pushing the responsibility to determine the readiness of dependancies to the 'service user' containers, can be problematic too. Because that is in-elegant when your container depends on many other disparate services.

Or potentially do both such mechanisms need to be provided?

[EDIT] Actually, come to think of it: You can also specify a post-start hook on the dependant (same) containers where to do the blocking. So that really aught to block crane from moving on to starting the next container, shouldn't it? However then you need to make sure that your dependancies all start up strictly in leaf order (bottom up). Else if mis-ordered your wait command will end up blocking forever.

Please correct me if i'm wrong about any of that.

**Comment by dreamcat4** [comment]
Oh right! Now I read #170 it would solve that last problem I mentioned (about fully controlling the startup order). ATM crane fails over to start containers in Alphabetical order, which would not be good enough.

@adrianhurt we still need to search the [docker/docker issue tracker](https://github.com/docker/docker/issues) for their plans to tackle this problem of containers waiting to go online / delayed startups.

**Comment by adrianhurt** [comment]
Thanks @dreamcat4 

I understand you hesitation. However, in my opinion, the problem here is to determine who should be in charge of this:
* Docker (CLI): IMHO Docker itself only can do one thing: when you run a container, wait until its dependent linked ports are exposed (of the other container, of course). Well, it's true it could be enough for many cases, but I'm not sure if it would be enough for every ones. I mean I don't really know if checking TCP connection to `db` container from `web` (using `nc` command, for example) would imply that the mysql-server is completely ready (I should try it), but anyway there could be cases in which you have other requisites to consider the container is completely ready, or even extra dependencies as I explain in the other issue. I think Docker can't do more because it only offers the tools to manage individual containers. It delegates to the user how to interconnect them and in which order.
* Each container: the user must add an additional logic inside each container before run the main process to check if everything is ready to use. Maybe it's the more logical way to solve this at a first glance.
* Compose/Crane: these are tools that try to manage multiple containers and their dependencies. IMO I think they should be in charge of this. They should have every information about the whole system (for every container) and their complete dependencies. Why should a container be started if its dependencies are not still ready. Imagine you lift with crane a whole project and the main process of the very first container fails. Until now, crane will lift every container in the exact order but every of them will fail. Shouldn't be more logical that crane warn you with a failed dependency of a container and skip that next container or even stop the deployment?. I think it is a job that should be done from outside the containers. I think it should be part of the orchestration of these containers.

I was been looking for this information 2 weeks ago within Docker and Compose issue trackers. And the only relevant information I got is [this issue](https://github.com/docker/compose/issues/374) in Compose. There are 64 comments (including the last one that is mine when I started with Docker) and there is no agreement…

But as I've said, in my opinion Crane (and Compose) should be in charge of orchestrate this. And each container should define how to check its readiness.

**Comment by adrianhurt** [comment]
Even more, regarding to this _'process-oriented' focus_… Now if you run `docker ps` or `crane status` you can see if each container is _up_ or not. But nothing else, nothing about their processes inside. What I would like to know is if they are correctly running or not. And this could be done with this approach simply testing them with this predefined command for each container.

**Comment by bjaglin** [comment]
For future reference, this was already touched upon in https://github.com/michaelsauter/crane/issues/74 and https://github.com/michaelsauter/crane/issues/148, which resulted in https://github.com/michaelsauter/crane/pull/159 still to be reviewed and merged.

I agree this is an orchestration concern, I just think there are many use-cases and it's not an easy discussion. Kubernetes, for example, distringuish liveness and readiness. Crane is a much more low-level tool, and I think we should aim at giving tools to build that, but without too much sugar/magic. Any feature introduced should somehow map to a concept from the Docker CLI IMHO.

For example, following-up https://github.com/michaelsauter/crane/pull/159, I want to suggest introducing a `pre-link` hook, defining an arbitrary, potentially blocking command to be run when a container is about to be linked into another one. I guess implementing readiness on top of that is trivial. In our experience, when starting a set of inter-dependent containers, what matters is that a container is reachable/available when another one that depends on it is about to start. Unfortunately, the PR queue is significant right now, so it will take some time.

**Comment by adrianhurt** [comment]
Yes, I think so. There could be more things to do (like monitoring or so), but I think the purpose of Crane is clear. It should be a way to define a whole structure of containers and orchestrate its deployment using this Docker CLI mapping. And in this case, defining the readiness of each container as well could be great to check the status of them. 

I was also thinking in a new command `test` or `check` that could simply test the readiness of targeted container. I'm now starting to add [Monit](http://mmonit.com/monit/) to my system, and I think `crane test container` could be a very easy way to check it.

**Comment by adrianhurt** [comment]
Hi @michaelsauter. Is this another issue on the roadmap?. There is more discussion now on the corresponding [docker-compose's issue](https://github.com/docker/compose/issues/374). I solved it adding a script to my image container called `wait-for-readiness.sh`. It simply checks if my container is ready or waits otherwise. It returns 0 if it is finally ready or 1 after a timeout. So, using a simple hook, I can get a dependent container waits to its readiness
```
hooks:
  web:
    pre-start: "docker exec -it db wait-for-readiness.sh"
```

I think this could be standardize to crane with something like:
```
containers:
  db:
    …
   health-check: mysql database -e "show tables"
  web:
    run:
      link: ["db:db"]
      …
    health-check: curl localhost:9000 | grep '<h1>Home</h1>'
```
or:
```
health-checks:
  db: mysql database -e "show tables"
  web: curl localhost:9000 | grep '<h1>Home</h1>'
  foo: health-check.sh
```
These health check declarations would be a simple command (that could call an ad-hoc script if necessary) executed by the container using `docker exec` and it should return 0 or 1.

As you see the difficult part is done. It'd only be necessary simplify and standardize it to crane clients.

**Comment by michaelsauter** [comment]
What you describe sounds good. However, I'm not sure how big of a need for this really exists. Crane already supports hooks which let you do this easily at orchestration level, and the other option is to ensure these kind of things inside the container.

So personally, I don't see a great need for this.
