### ISSUE TITLE
Ways to improve Documentation

### ISSUE THREAD

**Issue by dreamcat4** [michaelsauter/crane#174]
OK. I have read elsewhere (here in crane issues) that one reason why @michaelsauter is keeping features out is so that the main README file does not grow too big and unwieldy. As it would make it more mess, less small / concise and hard for people to quickly navigate or refer back to the most used crane documentation. The current Readme file is already on it's limits.

*If we really want a shot at adding any new features to Crane, we really need to think more about, and try to solve this problem. First of all.*

One possible way to keep the README documentation small and concise when adding new features is to not add them to the main README file at all. But rather, instead make 2nd, 3rd markdown file(s) for advanced usage(s). Even certain existing features of crane such as Groups etc. may already bloat the existing main Readme file. So in fact README.md could be even smaller.

@michaelsauter To improve in-page navigation, it is also a good idea to use either `doctoc` or `gh-md-toc` to generate a proper Github-compatible TOC inline, at the top of each markdown file(s). With clear enough headings and sub-headings organised, a TOC may improve navigation. But also can be a way to summarize / remind of options. Depending precisely how you wish to use it. *And that is a simple action we can take which does not add any new features to Crane whatsoever.*

Whilst on the subject, here is an example from one of my projects, with not only with inline TOCs generated by `doctoc` program (it is very easy!). But also I have hard-coded a navbar too along the top for jumping between just 3-4 markdown files. To be clear: I'm not suggesting it is necessary to go that far with documentation in this, the crane project! It is just another place can steal things from:

https://github.com/dreamcat4/docker-images/blob/master/pipework/0.%20Introduction.md

Finally - badges link:

http://shields.io/

Is very easy to use and create custom badges. Just by specifying a new image URL they get created automatically... you don't need to use only the pre-defined ones. They can be of anything. A badge will draw the eye, and highlight certain important data on the markdown page - because they stand out a lot more than regular text.

**Comment by dreamcat4** [comment]
My own suggestion how to basic re-structure, if move to multiple markdown files:

* Main README.md page - document all the options (as now)
* Examples section on it's own page
* Advanced Usage section on it's own page
* Any other misc stuff, contributing, how to build etc on seperate (last page).

So that is about 3-4 markdown pages in total. Including the main README.md

**Comment by adrianhurt** [comment]
I agree with that. The documentation is a bit hard now with an only README. It needs to be splitted to be more flexible. I would suggest to use the Wiki, but it seems that it's not possible to modify it within the same PR...

**Comment by dreamcat4** [comment]
Not, not agree wiki -1. Keep all documentation together with the source code.

**Comment by michaelsauter** [comment]
Open towards multiple markdown files in the source. I have a great dislike for wikis, so that will not happen :)

As a first step, I think the best candidate for extraction are guidelines about contributing and building Crane.
