### ISSUE TITLE
Set up CI hooks

### ISSUE THREAD

**Issue by bjaglin** [michaelsauter/crane#181]
As the number of contributors increase, we should have proper build status on PRs and on the README.md. I have done it quite easily in https://github.com/bjaglin/multiplexio for example.

**Comment by bjaglin** [comment]
cc @mishak87

**Comment by michaelsauter** [comment]
Sounds good. I started doing it but the build failed. Will have to investigate ...

**Comment by bjaglin** [comment]
I think it's related to some unit tests not so "unit", and requiring the `docker` client to be in the path. I am actually working towards fixing that in an unrelated PR where I need to stub it.

**Comment by bjaglin** [comment]
Nevermind, the `docker` stubbing is not the issue (tests handle the absence of `docker` somehow). It's actually related to a breaking change in https://github.com/fatih/color/commit/85fc70c416e81ae0e3ef7913d586d9ea5c15a295 - I'll look at updating the code so that it builds with the HEAD of fatih/color.

**Comment by michaelsauter** [comment]
Ah right, because it does not know about which versions we use. Yay for Go dependency management...

**Comment by bjaglin** [comment]
It's working now - for open PRs, closing/reopening does the trick
