### ISSUE TITLE
Add config file option to always pass --recreate to run

### ISSUE THREAD

**Issue by merwok** [michaelsauter/crane#196]
Hi!  We’re running a consul server in a container, using crane to manage a data-only container for persistent data and to link from or other apps containers.  Something in the consul config or dockerfile causes issues when the container is restarted, but things work great when the container is re-created.  I can run `crane run --recreate consul`, but I would like to put this option in the crane config file.  What do you think?

Thanks for crane, it’s quite nice.

**Comment by merwok** [comment]
(FTR, I did more tests with our consul container, and recreating the container is not enough to fix my issue.  So this crane ticket will not directly help me for this use case, but may be a good thing to add nonetheless.)

**Comment by michaelsauter** [comment]
Hmm, interesting idea. Will have to think about it.

**Comment by michaelsauter** [comment]
I'm going to close this one, because I think making `run` behave differently depending on the config might be confusing for users (especially if you work with multiple crane-based projects).
