### ISSUE TITLE
Stop hooks not executed on kill / rm -f

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#199]
For example `post-stop` is only executed for `crane stop`, not for `crane kill`.

I see 2 options:

1) Defining a `post-kill`, which is executed for `crane kill`. Probably `post-kill` should run for `rm -f`, too?

2) Executing `post-stop` also for `kill` and for `rm -f` if the container is currently running.

Personally, I like 2) for simplicity and clearer semantics around `rm -f`.

Thoughts?

**Comment by bjaglin** [comment]
:+1: for 2)
