### ISSUE TITLE
`crane rmi`

### ISSUE THREAD

**Issue by bjaglin** [michaelsauter/crane#216]
I am thinking about adding a `crane rmi` which would delete (`docker rmi`) all images that are not referenced by the config (independently of the presence of a `default` group), allowing to quickly reclaim space on a machine dedicated to run a stack handled entirely by crane. The problem is that this would not take any arguments, so the semantics don't map very well with other commands.

Thoughts?

**Comment by michaelsauter** [comment]
Interesting. I can definitely see the benefit. However, when I first saw the title of this issue, I thought you wanted to introduce a command that would remove all images defined in the crane config.

I don't really want to turn the semantics upside down for this command only :)

Actually, I think this is outside the scope of Crane. However, maybe Crane can help you build what you want. E.g. if Crane would offer you a way to retrieve all images referenced in the config (or the given target), you could build a script that would delete all images not in that result?

**Comment by dreamcat4** [comment]
@bjaglin There is the Sherdock web-GUI tool, just mentioned in other related issue (discussion of orphaned containers).

**Comment by bjaglin** [comment]
fair enough, thanks for your suggestions!
