### ISSUE TITLE
support additional tags

### ISSUE THREAD

**Issue by tmc** [michaelsauter/crane#222]
Having a tag associated with a build is useful but "latest" is assumed in docker's FROM.

Supporting additional tags while provisioning would be nice.

**Comment by bjaglin** [comment]
(old) related discussion: https://github.com/michaelsauter/crane/issues/120

**Comment by michaelsauter** [comment]
Crane's build support is minimal, and going to stay that way. If you need more, you will need to look at other tools, sorry.

**Comment by tmc** [comment]
This is unfortunate -- I was almost through replacing a complex set of build scripts. tagging :latest is the only missing thing. I'm using git shas (and additional data data for diffs) as tags FWIW.

**Comment by tmc** [comment]
Doing a no-op re-provision with "latest" in an env var is an ok hackaround.

**Comment by michaelsauter** [comment]
What is going to happen though is that I'm going to move `dockerfile` into a `build` map, to at least be able to extend it in the future (if someone wants to contribute that).

Glad you found a workaround in the meantime.
