### ISSUE TITLE
stop -t 100

### ISSUE THREAD

**Issue by saz59** [michaelsauter/crane#227]
Hi.
In the configuration file, specify the time to wait for completion of processes for the command stop.
Regards.

**Comment by michaelsauter** [comment]
As in, you would like to have that feature?

If so, I think this would be very low priority for me, but I would be open for contributions.

**Comment by saz59** [comment]
Some containers require more time than the default to safely stop. 
Now I use docker to stop such containers.
And then I use the 'crane stop' for other containers.
I would like to use only the crane.

**Comment by michaelsauter** [comment]
I see why this can be useful.

However, as I said, I don't see a pressing need for it, so if you want to use Crane with this, you probably have to contribute yourself. It should not be a major task as you should be able to follow the example of e.g. the `start` configuration.
