### ISSUE TITLE
ERROR: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dreamcat4** [michaelsauter/crane#230]
Versions tried: `v2.0.0`, `v2.0.1`, `master`.

This happens on `crane create` command. Not sure why. 

```sh
$ crane create -v deluge.id
Using configuration file `/home/id/docker-images/crane.yml`
Command will be applied to: deluge.id
If needed, also starts: deluge.config.id

Creating container deluge.id ... ERROR: runtime error: invalid memory address or nil pointer dereference
id@emachines-e520:~/docker-images$ 
```

```sh
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:40:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:40:42 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by michaelsauter** [comment]
Could you paste the crane configuration?

**Comment by dreamcat4** [comment]
OK. It seems when I removed the following key it worked again (after upgrading from `v1.1.1` --> `2.0.x`)

```yaml
  deluge.id:
    run:
      net: none
```

So I guess it was the `net: none` key under `run:` map?

**Comment by dreamcat4** [comment]
@michaelsauter. OK In fact yes it seems. To reproduce this I just made it so the entire config to be this:

```yaml
  deluge.id:
    image: dreamcat4/deluge
    run:
      net: none
```
And nothing else. Commenting out the last 2 lines and then it works. So there seems to be some kind of issue around the `net:` key somehow. Not sure why yet.

**Comment by dreamcat4** [comment]
Well it seems for crane v2 the same syntax / key manes for this bit still same as before.

When I put `net: none`, `net: host`, and `net: container:tvh`. It still generates the same error message.

When I put `net: bridge`. Then the error does not occur. Perhaps because the key is dropped from the args / flags. Since being the default networking option. Dunno what's wrong here.

**Comment by dreamcat4** [comment]
Let me just say I'm not sure about where the error acutally might be. But if net mode is left the default, or specified as `bridge`, then this bit of code isn't executed:

https://github.com/michaelsauter/crane/blob/20fa0ca2573204496abaeca770bb195bff6f0a5e/crane/container.go#L700-L705

And there is no error message. However if I disable the "if not bridge" outer if statement (so will always go into that bit). Then the error does appear in all conditions, including when the mode is bridge too.

That bit of the code used to look like this:

https://github.com/michaelsauter/crane/blob/b16e5d01a7020cc70436f0ab653e871818057817/crane/container.go#L650-L663

Sorry. But I confess I don't really know / understand what's going on with it.

**Comment by dreamcat4** [comment]
Specifically this 1 line (when exercised):

```go
	args = append(args, "--net", cfg.Container(c.RunParams.Net()).ActualName())
```

@ here

https://github.com/michaelsauter/crane/blob/20fa0ca2573204496abaeca770bb195bff6f0a5e/crane/container.go#L703

**Comment by dreamcat4** [comment]
@michaelsauter I think I found a fix for this. Was not very hard in the end...

If change that 1 line of code to this:

```go
args = append(args, "--net", c.RunParams.Net())
```

Then it is like the other ones above & below. And recompile. No error message anymore. And the `--net host` text appear OK in the command printout. That seems to have fixed the problem.

It's a very simple change so I didn't bother going to the trouble of making a PR of it. But perhaps you could roll it into your next changes? Many thanks.

**Comment by combro2k** [comment]
@dreamcat4 had the same issue :-)

**Comment by michaelsauter** [comment]
@dreamcat4 Thanks for reporting and investigating! I'm going to fix it soon.

**Comment by combro2k** [comment]
Ive compiled it with the suggestion of dreamcat4.

Perhaps create an if statement when there is no : used?

Sent from TypeMail




-------- Original Message --------

**Comment by michaelsauter** [comment]
@dreamcat4 Actually, your proposed solution is incorrect. We need the actual name, but need to ensure we actually have a container.

**Comment by dreamcat4** [comment]
Thanks!
