### ISSUE TITLE
Proposal: option to run a container (and every dependencies) with `detach` attribute set to false

### ISSUE THREAD

**Issue by adrianhurt** [michaelsauter/crane#237]
I'll try to explain it better with an use case.

I usually use a crane.yml file for development and I've set the attribute `detach: true` for the most of containers. However, for production I use Systemd with a unit file for each service (container). And it requires that I have to unset every `detach` attribute (commenting them). So the problem is that I need 2 different crane.yml files.

I don't know if there would be more use cases for that issue, but I think it would be great to have an option to tell crane to run every container with `detach: false` for every container. Something like:
```
crane run --attach-all container
```

**Comment by michaelsauter** [comment]
Hmm. I'm not sure this is generic enough to warrant its own flag. Maybe some trickery with environment variable would be enough for you?

**Comment by michaelsauter** [comment]
Maybe `crane.yaml` would need a "function" of sorts where you can set a default, and override with environment variable. unfortunately the standard shell way does not work.

**Comment by adrianhurt** [comment]
I've tried using an environment variable like:
```
detach: $DETACH_CONTAINERS
```
But the yaml compiler raises this error:
```
ERROR: yaml: unmarshal errors:
  line 21: cannot unmarshal !!str `$DETACH...` into bool
```
It seems the environment variable substitution is made after compilation.

Thinking about your last suggestion… I use a section for aliases within crane.yml with some variables
```
aliases:
  - &db_user MYSQL_USER=$MYSQL_USER
  - &db_password MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  - &db_database MYSQL_DATABASE=$MYSQL_DATABASE
  - &mysql_image mysql:5.7.9
  - &base_image ubuntu:14.04
  - &detach true
```
Maybe it could be interesting to standardize it and adding the ability to override any of them with something like:
```
crane --alias "detach=true" run container
```
Similar to `docker -e "…"` …

The pity is that this is a problem of YAML which needs urgently a version 2.0 with functions and variables like LESS or SASS, for example...

**Comment by michaelsauter** [comment]
https://github.com/michaelsauter/crane#configuration says something about environment variables at the very end. Maybe it only works for strings though? Never tried for booleans I guess.

**Comment by adrianhurt** [comment]
Oh, yes. I understand now. I thought the yaml compiler was the one that made the environment substitution but it doesn't. It simply put the same string and it goes to Docker CLI directly with the `$X` pattern. So, yes it only works for string values because the yaml compiler raises an error if it expects a boolean.

**Comment by adrianhurt** [comment]
Something like [this Go CSS preprocessor](https://github.com/yosssi/gcss) adapted to create a YAML preprocessor with variables and mixins would be awesome as an independent project. I don't know Go, but if anyone reading this feels motivated… hehehe. There are more examples of SASS compilers in Go out there.
