### ISSUE TITLE
Statically compiled version of crane

### ISSUE THREAD

**Issue by jesper** [michaelsauter/crane#246]
Is there a statically compiled version of Crane available? If not, are there any instructions on how to build it myself (statically)?

```
$ file crane_linux_amd64 
crane_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
```

**Comment by jesper** [comment]
Setting this env variable at compile time gave me a statically compiled version of crane:
CGO_ENABLED=0

**Comment by michaelsauter** [comment]
Nice, and thanks for sharing the solution!
