### ISSUE TITLE
Implicit unique / ad-hoc behaviour

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#265]
Instead of a pre-defined `unique` key, we could add this behaviour implicitly. 

If a command is passed on the command line, the container gets a timestamp attached to it's name, and the following changes are made to the configuration:

* `publish`, `publish-all` and `detach` are disabled
* `rm` is enabled

Crane would then not care at all about these ad-hoc containers, for example when calling `crane rm` the container would not be removed.

We could have two options `--publish` and `--detach` to override the default behaviour, but I'm not sure it's worth the effort.

The advantage of the proposed change would be:

* No separate configuration key (which name might be difficult to understand)
* It is possible to quickly launch a container with similar configuration without planning for this in advance in the config
* All extra branches in the code related to unique containers can be removed as Crane will only care about the configured containers
* Projects with 2 containers (e.g. a container for a Rails server, and one for ad-hoc rake commands etc.) can simplify the configuration to just one

Since the feature is marked as experimental, this could be released as 2.7.0.

Any thoughts?

**Comment by bjaglin** [comment]
That makes a lot more sense to me than the current somehow-hacky `unique` behavior, and I like the UX :+1:

**Comment by michaelsauter** [comment]
Good to hear :)
