### ISSUE TITLE
Add crane renew command

### ISSUE THREAD

**Issue by MetalMatze** [michaelsauter/crane#268]
I often find myself typing something like:
```bash
crane stop container && crane rm container && crane start container
```

I propose an additional command e.g. `crane renew` or something different.

Thanks!

**Comment by michaelsauter** [comment]
`crane run` should do exactly that - with the exception that it kills the container. Is that something you want to avoid?

**Comment by MetalMatze** [comment]
I guess that's my bad. 
Seems like I overlook that one. 
Got used to using `start`, `stop` & `rm`.

Thanks!
