### ISSUE TITLE
2.7.0 broken on Ubuntu 15.10 without musl

### ISSUE THREAD

**Issue by mknecht** [michaelsauter/crane#284]
I can download, make executable and run 2.5.2 and 2.6.0 without problems. With 2.7.0 I get this:

  $ ~/Downloads/crane_2.7.0 
  bash: /home/murat/Downloads/crane_2.7.0: No such file or directory

  $ file ~/Downloads/crane_2.7.0 
  /home/murat/Downloads/crane_2.7.0: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped

I don't have musl installed, so maybe that's the problem, but I don't see why I suddenly should need it.

**Comment by dreamcat4** [comment]
I can build crane from go source on ubuntu 15.10, and it works just fine...

Did put up some instructions at one point how to do it. But maybe they got lost or something / cant remember. Anyway for that you would need to install go first, and setup yourself with a go build environment.

**Comment by mknecht** [comment]
@dreamcat4 I am not building it from source, I am using the prebuilt binaries for linux 64bit. It works for many versions before, but not for 2.7.0.

**Comment by michaelsauter** [comment]
Hmm interesting. I did change how the binaries are built, so it must be somehow related.

Versions below 2.7 were built on Ubuntu 14.04 using gox. Version 2.7.0 was built inside a Docker container running Apline 3.3, using the built-in cross compilation features of Go. I made that change to be more flexible and be able to have the same build environment between various machines.

@mknecht What does `file ~/Downloads/crane_2.6.0` say?

**Comment by dreamcat4** [comment]
@michaelsauter Well there is your answer. Apline linux uses libmuscl, not glibc hence the incompatibilty. You probably would find it simplest way to just build from some other base image instead of Alpine.

For that I recommend using `ubuntu:16.04`, or `ubuntu:xenial-20160317` for a fixed image snapshot. Since 16.04 is due to be officially released in about 3 weeks time.

Otherwise you know, debian, or else you are hacking with glibc into apline, which would likely be very problematic etc

**Comment by michaelsauter** [comment]
I see. I thought the Go binary would be independent from the system I'm using when building, so didn't think much about it.

**Comment by michaelsauter** [comment]
I've made a change to compile the binaries statically now: https://github.com/michaelsauter/crane/commit/77a7ca7537c052b5b1ee6e481a1a2c3e55d2807c, and updated the pre-built binaries.

@mknecht Could you test if that works for you now?

**Comment by mknecht** [comment]
@michaelsauter yep, that fixes it … awesome, thank you! :+1: 

re independent: Yes, all except the glibc. [There are workarounds](http://www.blang.io/posts/2015-04_golang-alpine-build-golang-binaries-for-alpine-linux/) but maybe it's for now simplest to mark the releases as needing glibc, i.e. crane_linux_amd64_glibc?

**Comment by michaelsauter** [comment]
I don't see downsides in disabling cgo and have a static binary going forward. Anything that I miss why I should prefer a dynamic binary depending on glibc?

**Comment by mknecht** [comment]
size. glibc will prob be huge, so maybe musl after all? but haven't looked into this topic much, might be other implications.

**Comment by mknecht** [comment]
(It def be good to find out why the Golang guys made that default choice in the first place. :) )

**Comment by michaelsauter** [comment]
Hmm, the binary size is almost the same. Definitely not something that I worry about. I didn't read a lot about it, but quick googling yielded http://stackoverflow.com/a/1993407, after which static compiling sounded fine to me.

**Comment by michaelsauter** [comment]
From https://golang.org/cmd/cgo/

> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling. You can control this by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it. The go tool will set the build constraint "cgo" if cgo is enabled.
