### ISSUE TITLE
--tag conflict with registry port

### ISSUE THREAD

**Issue by fastinetserver** [michaelsauter/crane#295]
Crane 2.9.0:
When registry uses a port number e.g. myregistry.com:5000 tag is placed instead of the port.
Expected:
myregistry:5000/user/nginx-image:mytag
Received:
myregistry:mytag

---------------------------------------
If possible would be awesome to have 
crane enter container-name [command]
to run:
docker -it container-name /bin/bash

**Comment by michaelsauter** [comment]
Oh ;) That's a bug.

Regarding your feature request: would be better suited in a different ticket. However, I can already say that something like this won't get introduced since Crane maps to Docker commands. As long as there is not `docker enter`, a `crane enter` is unlikely. Another issue with your proposal is that you assume `/bin/bash` is a thing in the container, which it might not be (e.g. in Alpine based containers). You might get close to your desired result by using `crane exec`.

**Comment by michaelsauter** [comment]
Hmm, https://github.com/michaelsauter/crane/blob/master/crane/container_test.go#L125-L153 seems to cover exactly this case. Are you sure this is broken?

**Comment by fastinetserver** [comment]
Here is the output without a tag (works fine):
$ crane push
Pushing image reg.mydomain.com:5000/bean/production-slivkoed-data ...
The push refers to a repository [reg.mydomain.com:5000/bean/production-slivkoed-data]
471543376001: Layer already exists 
-----------------------------------------------------------------
Let's set the tag now:
$ export CRANE_TAG=latest
$ crane push
Pushing image reg.mydomain.com:latest ...
The push refers to a repository [docker.io/library/reg.mydomain.com]
92dccac4f356: Preparing 
5f70bf18a086: Preparing 
bbf4634aee1a: Preparing 
64d0c8aee4b0: Preparing 
4dcab49015d4: Preparing 

The lines in the test seem to be right, but looks like they do not cover this issue.

Offtopic: Thank you for the great tool, Mike !!!

**Comment by michaelsauter** [comment]
Oh, can you share the relevant bit of your config? I suspect the image definition does not have a tag, and then Crane does the wrong thing by assuming there is a tag (named `5000/bean/production-slivkoed-data` in your case).

My initial guess is that we need to make sure the tag does not contain characters such as `/`.

**Comment by fastinetserver** [comment]
Please send me a direct message to either fastinetserver@gmail.com or skype: zxscript.com i'll share my PRIVATE yaml/jinga2 templates and assist you to reproduce the issue.

**Comment by michaelsauter** [comment]
If you could just confirm that the config does not have an image tag, just a name, that would be enough.

**Comment by fastinetserver** [comment]
yes, no image tag in the crane.yaml file

**Comment by michaelsauter** [comment]
Cool. I'll probably find time to fix it next week and release as 2.9.1. Sorry for the wait.

**Comment by fastinetserver** [comment]
Thank you, Mike ! Looking forward for it !
