### ISSUE TITLE
default group exclude option

### ISSUE THREAD

**Issue by fastinetserver** [michaelsauter/crane#296]
Mike,

Feature request: Would be great to have default_exclude option.
Reasons: When there are lots of containers and we gradually add more (for each service/process), so each time i add a service or bg-job i have to add more containers to the default group, to make sure default group does NOT include stateful-data-containers.
So idea is that, by DEFAULT the default group would still use __all__ the containers except the ones defined with default_exclude option.
Another option might be to use a minus sign like this:
groups:
  default: ["-stateful-data-container"]
  databases: ["database1", "database2"]
  services: ["service1", "service2"]

Please note: That cli --exclude or CRANE_EXCLUDE, can NOT be used within crane.yaml file, so they would require to keep an extra bash script on the system.

Not sure if applicable, but i really like how django's ORM uses .filter() and .exclude(), e.g.:
good_team = People.objects.filter(bio__icontains='good boy').exclude(about__icontains='bad boy')

Please let me know if there's another way to define exclusion within crane.yaml file.

Thank you !

**Comment by michaelsauter** [comment]
2 things:

* Do you really need to exclude stateful data containers? For example if you have container A depending on container B, then if you `crane rm A`, it does not affect `B`. You only remove `B` if you do `crane rm`.

* As you say, using `exclude` on the CLI is already possible. I don't think using wrapper scripts is a bad thing. I myself use wrapper scripts for Crane, and like the flexibility this gives without complicating Crane itself.

So as a first reaction, I'm opposed to changing this. If there is more demand for this and/or someone willing to implement it, I might reconsider.

**Comment by fastinetserver** [comment]
Mike, thank you for a quick reply !

1) Yes, that is the idea, that excluded containers should be EXPLICITLY removed, because it is dangerous to do `crane run` or `crane rm` - we can loose stateful containers. (Especially, when crane is operated by the client).

2) I try to avoid scripts when possible, and instead use jinja2 templates with python script to generate ready to use crane.yaml files. So in my case i simply create an UNMAINTAINABLE list for the default group or even move the data folders to the host.

3) RE: first-reaction: You obviously have more experience with docker and crane :)

**Comment by michaelsauter** [comment]
Closing this as I don't see it to be really necessary. You can achieve what you need via other means.
