### ISSUE TITLE
compose2crane feature

### ISSUE THREAD

**Issue by roscopecoltran** [michaelsauter/crane#317]
Hi guys,

Hope you are all well !

I was wondering if there is a tool to convert docker-compose.yml, v1 and v2, to a crane.yml file.

The generate options seems to convert crane -> docker-compose.

Am I correct ?

Thanks for your reply.

Cheers,
Richard

**Comment by roscopecoltran** [comment]
Also, is there any template with all the references available in crane if I would like to use confd for eg ?

**Comment by michaelsauter** [comment]
Yes you are correct, the generate feature only works with a crane configuration as the source. It certainly would be possible to convert docker-compose to crane, but I'm not entirely sure how easy it would be or if it would be in the scope of crane at all.

About your second question - do you want to generate a confd configuration using the generate command?

**Comment by michaelsauter** [comment]
I'm closing this as Crane 3 can now read docker-compose files, so there is no for conversion any longer.
