### ISSUE TITLE
fix compatibility with new Docker versioning scheme

### ISSUE THREAD

**Issue by bjaglin** [michaelsauter/crane#318]
It looks like the new Docker versioning scheme (https://github.com/docker/docker/pull/31075), already available in the Beta channel, is breaking crane's version detection.

**Comment by michaelsauter** [comment]
Oh right.

I'm actually working on a new (major) version of Crane :) 

For the versioning, I'm probably going to require at least Docker >= 1.10, which seems to be the current minimum, or Docker > 17.x.

**Comment by bjaglin** [comment]
OK, good to know - I think it makes sense to maintain the 2.x branch anyway, so I'll probably open a PR as well.

**Comment by michaelsauter** [comment]
Sure, there should be a release to fix it. But - I can't reproduce the issue. I'm working on MacOS at the moment, and after updating to `Docker version 17.03.0-ce, build 60ccb22`, Crane continues to work. What's the error you get? Or do you think it's logically broken?

**Comment by bjaglin** [comment]
Apologies for the noise, I cannot reproduce it either.

A colleague couldn't run Crane at all (no output) with Docker For Mac Edge (`Docker version 17.03.0-ce, build 60ccb22`) and I concluded too fast that it was linked to the versioning scheme, but trying it myself and looking at the code, I don't see how this could be the case, so it was probably another issue, most likely related to Docker itself.
