### ISSUE TITLE
hostname seems to be prefixed but is not in docker --verbose output

### ISSUE THREAD

**Issue by dfherr** [michaelsauter/crane#324]
minimal config elements:
```
postgres:
    hostname: "postgres"
    net: "dev"
```

gives this crane run --verbose output:

`docker run --hostname postgres --net prefix_dev`

hostname for the postgres services is accessible under `prefix_postgres.prefix_dev` though

**Comment by michaelsauter** [comment]
I think this is actually correct behaviour. If you type `hostname` in your container, it should say `postgres`.
