### ISSUE TITLE
link option does not add container to /etc/hosts if it's not defined in the crane.yaml file

### ISSUE THREAD

**Issue by fastinetserver** [michaelsauter/crane#331]
I have 2 projects under crane 2.9.0:
first_project.yaml) Running Mongo db first_project.yaml
second_project.yaml) that has a container linked to mongo, which includes:
```
containers:
    dev-secondproject-gunicorn:
        run:
            hostname 'dev-secondproject-gunicorn'
            link: [
                  'dev-firstproject-mongo:mongo',
                  'dev-secondproject-postgresql:postgresql'
            ]

```
However, when i **run** dev-secondproject-gunicorn its /etc/hosts contains only dev-secondproject-postgresql. I guess, this comes from the fact that dev-firstproject-mongo is defined only in the first_project.yaml and therefore not inculded into the **allowed** variable/list.

Is there any workaround ?

Thank you for Crane !

**Comment by michaelsauter** [comment]
I see. Two options come to mind:

* Combine the 2 YAML files into one
* Upgrade to Crane 3 and make use of Docker networks. There you won't run into those kind of issues.

**Comment by fastinetserver** [comment]
Unfortunately, A) is not an option, because mongo host is supposed to be shared among several separate projects.
B) Might take some time to check and adjust all the projects for 3.x

Therefore, i had to:
a) On the mongo host: publish the port of mongo to the internal-ip:
`            publish: ['172.17.0.1:27017:27017']`
b) On the client(dev-secondproject-gunicorn):
`            add-host: ['mongo:172.17.0.1']`

Which might be not elegant enough, but works till the moment i'm brave enough to switch to crane 3.x

Would be great if it was possible to specify extra parameters for run in the .yaml file:
E.g. if i run:
` crane run -v dev-secondproject-gunicorn`
then just copy paste the output and add --link dev-firstproject-mongo:mongo , it works, but it is not as good and simple as **crane run**.

**Comment by michaelsauter** [comment]
Thanks for writing up your solution! I highly recommend checking out Crane 3, the upgrade path shouldn't be too difficult and it has lots of improvements over Crane 2.
