### ISSUE TITLE
Initial sync never completes

### ISSUE THREAD

**Issue by jamescowie** [michaelsauter/crane#332]
I created a very simple test that consisted of a single PHP file and map that do the accelerated mount. However its never completing the initial sync. Leaving it running for over an hour produces no further output. 

Im running Crane PRO 3.3.3 and the latest stable docker for mac.

**Comment by michaelsauter** [comment]
Sorry to hear. That should not happen!

To help me debug the issue, could you paste the output of `crane am logs <your-service>`?

**Comment by jamescowie** [comment]
Closing issue. After a reboot and some patience it worked as expected.
