### ISSUE TITLE
runtime nvidia/gpu support

### ISSUE THREAD

**Issue by x0rzkov** [michaelsauter/crane#354]
Hi,

Hope you are all well !

Can we add support for --runtime=nvidia or --gpu=all parameters in crane ?

That would be awesome.

Cheers,
X

**Comment by michaelsauter** [comment]
Sure! However, it is not a requirement for me so please provide a PR if possible.

**Comment by x0rzkov** [comment]
I do not knoe how to code that but I have a pro version and it is quite important for me.
