### ISSUE TITLE
Convert crane.yml to docker-compose.yml

### ISSUE THREAD

**Issue by ducky710** [michaelsauter/crane#355]
I've been using crane for a while but I've lately been wanting to just go back to regular docker-compose, I have a ton of stuff configured in my crane file and was wondering if there was a way to export everything into a docker-compose.yml file.

**Comment by michaelsauter** [comment]
Sorry, there's nothing like this ... Crane only supports this "the other way around": it can read docker compose files, but doesn't do conversion. Sorry.
