### ISSUE TITLE
Convert crane.yaml to docker-compose.yaml

### ISSUE THREAD

**Issue by github-daniel-stoian** [michaelsauter/crane#363]
Hello,

We have a pretty large crane.yaml and we want to translate it to a docker-compose.yaml format for other projects.
Can crane generate command do that ? Or there is another way to translate a crane config into docker-compose  v3 config ?

Thank you.

**Comment by bjaglin** [comment]
Hi @github-daniel-stoian :wink: 

There is no built-in mechanism, and AFAIK, you are stuck on the 2.x branch which is effectively EOL. You can probably start from https://github.com/michaelsauter/crane-templates/blob/master/docker-compose.tmpl if you want to derive a docker-compose v3 config.

**Comment by github-daniel-stoian** [comment]
Thank you Brice.

**Comment by github-daniel-stoian** [comment]
Hello again,

I've give it a try with crane generate command using https://github.com/michaelsauter/crane-templates/blob/master/docker-compose.tmpl and it's working.

Unfortunately we need to generate more custom templates inquiring elaborated operations:
- skipping certain services if name it's not matching a pattern
- edit ports/labels/environment
- etc

For that we need more functions added into [template function](https://github.com/michaelsauter/crane/blob/079b12a3cc96899a34e19ee72ece8c5d6f806a55/crane/unit_of_work.go#L218) like :
- strings.Contains
- strings.Split
- etc

Something like [Funcs](https://pkg.go.dev/text/template#Template.Funcs): 
        var (
		funcs     = template.FuncMap{"contains": strings.Contains, "split": strings.Split}
	)
        tmpl, err := template.New(templateName).Funcs(funcs).ParseFiles(templateFile)

On top of that, we need this function on v2.11.1 ... because we are stuck on that version.
What will be a course of actions for this change for older version ?

Thank you.

**Comment by michaelsauter** [comment]
@github-daniel-stoian I suggest you fork this repo and make the changes you require to v2 in your repo.

**Comment by github-daniel-stoian** [comment]
I was thinking the same thing. Thank you.
