### ISSUE TITLE
consistent order when explicit order is not provided 

### ISSUE THREAD

**Issue by bjaglin** [michaelsauter/crane#65]
Since the introduction of the optional `order` attribute in the config, crane commands against a set of containers defined in a config that do not provide an explicit order (i.e. when the automatic ordering kicks in) are not deterministic, due to the go behavior of shuffling randomly the entries when iterating over a map in `ContainerMap::extractDependencies()`.

This is not a semantic problem as such, since dependencies should all be recognized, but it's very confusing to see the order jumping between each `crane status` for example, and makes lookup difficult. Providing an explicit order is of course a solution, but with a growing number of containers, it results in a lot of duplication (unless we allow order to use groups as in https://github.com/michaelsauter/crane/issues/52 maybe?).

To get a consistent order across runs, we could either use a simple ordering `ContainerMap::extractDependencies()` (alphabetical), or include the (sorted) list from the config, and use this collection to iterate (since we don't use the fact that containers are mapped by name anyway).

**Comment by dreamcat4** [comment]
@bjaglin @michaelsauter Sorry to be a pain again. But I am very interested in this supposed `order:` attribute. Cannot find it documented of shown in the README file. Is it a ghost feature?

Can see that crane starts containers strictly alphabetically… would an `order:` attribute be a way to change the container startup order in different `groups` to be something possibly non-alphabetical?

(I mean, for situations where inherent container dependancies are not affecting the ordering).

**Comment by michaelsauter** [comment]
Ha, I forgot about it. Not even sure if it exists :) Probably not if not mentioned in the readme ... it might have been removed with the introduction of groups ...

**Comment by bjaglin** [comment]
@dreamcat4 https://github.com/michaelsauter/crane/issues/81
